import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ExternalLink, GraduationCap, Mail, Phone, Plus, Shield, Sparkles, Trash2, Users, UserRound, X } from 'lucide-react';
import { api, post, put, remove } from '../services/api';
import { route } from '../services/navigation';
import { initials, roleNames } from '../services/roles';
import { ProgressBar, LessonChecklist } from '../components/ProgressUi';

function PageHead({ eyebrow, title, subtitle, action }) { return <div className="account-heading"><div><div className="eyebrow muted">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
function Stat({ icon: Icon, value, label, tone = '' }) { return <div className="stat-card"><span className={`stat-icon ${tone}`}><Icon size={22} /></span><strong>{value}</strong><small>{label}</small></div>; }
function PersonChip({ user, onNameClick }) { return <span className="person-chip"><span className="person-avatar">{user.avatar ? <img src={user.avatar} alt="" /> : initials(user)}</span><span><span className="person-chip-name">{onNameClick ? <button type="button" className="person-name-action" onClick={onNameClick}>{user.firstName} {user.lastName}</button> : <strong>{user.firstName} {user.lastName}</strong>}</span><small>{user.email}</small></span></span>; }
const emptyUser = { firstName: '', lastName: '', email: '', password: '', role: 'student', curatorId: '', assignedCourses: [] };
const safeProfileUrl = value => { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } };

function UserProfilePreview({ user, onClose }) {
  const portfolioUrl = safeProfileUrl(user.portfolioUrl);
  const linkedinUrl = safeProfileUrl(user.linkedinUrl);
  useEffect(() => { const handleKeyDown = event => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', handleKeyDown); return () => window.removeEventListener('keydown', handleKeyDown); }, [onClose]);
  return <div className="user-profile-preview-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="user-profile-preview" role="dialog" aria-modal="true" aria-labelledby="user-profile-preview-title"><button className="user-profile-preview-close" onClick={onClose} aria-label="Закрыть профиль"><X size={19} /></button><div className="user-profile-preview-identity"><span className="user-profile-preview-avatar">{user.avatar ? <img src={user.avatar} alt="" /> : initials(user)}</span><div><span className={`role-badge role-${user.role}`}>{roleNames[user.role]}</span><h2 id="user-profile-preview-title">{user.firstName} {user.lastName}</h2><a className="user-profile-preview-email" href={`mailto:${user.email}`}><Mail size={15} />{user.email}</a></div></div><div className="user-profile-preview-body"><div className="user-profile-preview-label">О себе</div><p>{user.bio?.trim() || 'Пользователь пока ничего не рассказал о себе.'}</p><div className="user-profile-preview-label">Ссылки</div><div className="user-profile-preview-links">{portfolioUrl && <a href={portfolioUrl} target="_blank" rel="noreferrer"><span>Портфолио</span><ExternalLink size={15} /></a>}{linkedinUrl && <a href={linkedinUrl} target="_blank" rel="noreferrer"><span>LinkedIn</span><ExternalLink size={15} /></a>}{!portfolioUrl && !linkedinUrl && <p>Ссылки пока не добавлены.</p>}</div></div><button className="outline-button user-profile-preview-done" onClick={onClose}>Закрыть</button></section></div>;
}

export function Dashboard({ user, courses, navigate }) {
  if (user.role === 'admin') return <AdminDashboard courses={courses} navigate={navigate} />;
  if (user.role === 'curator') return <CuratorDashboard navigate={navigate} />;
  if (user.role === 'teacher') return <TeacherDashboard user={user} courses={courses} navigate={navigate} />;
  return <StudentDashboard user={user} courses={courses} navigate={navigate} />;
}

function AdminDashboard({ courses, navigate }) {
  const [stats, setStats] = useState(null);
  const [users, setUsers] = useState([]);
  const [progress, setProgress] = useState([]);
  const [tab, setTab] = useState('users');
  const [form, setForm] = useState(null);
  const [editId, setEditId] = useState(null);
  const [viewing, setViewing] = useState(null);
  const [error, setError] = useState('');
  const refresh = async () => { const [a, b, c] = await Promise.all([api('/admin/stats'), api('/admin/users'), api('/admin/progress')]); setStats(a); setUsers(b); setProgress(c); };
  useEffect(() => { refresh().catch(err => setError(err.message)); }, []);
  const submit = async event => {
    event.preventDefault(); setError('');
    try {
      const payload = { ...form, curatorId: form.curatorId || null };
      if (!payload.password) delete payload.password;
      if (editId) await put(`/admin/users/${editId}`, payload);
      else await post('/admin/users', payload);
      setForm(null); setEditId(null); await refresh();
    } catch (err) { setError(err.message); }
  };
  const beginEdit = person => { setEditId(person._id); setForm({ firstName: person.firstName, lastName: person.lastName, email: person.email, password: '', role: person.role, curatorId: person.curatorId || '', assignedCourses: person.assignedCourses || [] }); };
  const deleteUser = async person => { if (!window.confirm(`Удалить пользователя ${person.firstName} ${person.lastName}?`)) return; try { await remove(`/admin/users/${person._id}`); await refresh(); } catch (err) { setError(err.message); } };
  return <main className="account-page"><div className="account-width"><PageHead eyebrow="АДМИНИСТРИРОВАНИЕ" title="Панель администратора" subtitle="Пользователи, курсы и результаты обучения в одном месте" action={<button className="primary-button" onClick={() => { setForm({ ...emptyUser }); setEditId(null); setTab('users'); }}><Plus size={18} /> Создать пользователя</button>} />
    {error && <div className="form-error">{error}</div>}
    <div className="stats-grid"><Stat icon={Users} value={stats?.users ?? '—'} label="Всего пользователей" /><Stat icon={GraduationCap} value={stats?.students ?? '—'} label="Учеников" tone="mint" /><Stat icon={BookOpen} value={stats?.teachers ?? '—'} label="Учителей" tone="peach" /><Stat icon={UserRound} value={stats?.curators ?? '—'} label="Кураторов" tone="purple" /><Stat icon={BookOpen} value={stats?.courses ?? '—'} label="Курсов" /><Stat icon={Sparkles} value={stats ? `${stats.averageProgress}%` : '—'} label="Средний прогресс" tone="mint" /></div>
    <div className="dashboard-tabs"><button className={tab === 'users' ? 'active' : ''} onClick={() => setTab('users')}>Пользователи</button><button className={tab === 'courses' ? 'active' : ''} onClick={() => setTab('courses')}>Курсы</button><button className={tab === 'progress' ? 'active' : ''} onClick={() => setTab('progress')}>Прогресс</button></div>
    {tab === 'users' && <section className="dashboard-panel"><div className="dashboard-panel-head"><h2>Пользователи</h2><span>{users.length} аккаунтов</span></div>{form && <form className="account-form" onSubmit={submit}><div className="panel-heading"><h3>{editId ? 'Редактировать пользователя' : 'Новый пользователь'}</h3><button type="button" onClick={() => setForm(null)}><X size={18} /></button></div><div className="form-grid"><label>Имя<input required value={form.firstName} onChange={event => setForm({ ...form, firstName: event.target.value })} /></label><label>Фамилия<input required value={form.lastName} onChange={event => setForm({ ...form, lastName: event.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Пароль<input type="password" required={!editId} minLength={10} value={form.password} placeholder={editId ? 'Оставьте пустым, чтобы не менять' : 'Не менее 10 символов'} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label>Роль<select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}>{Object.entries(roleNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{form.role === 'student' && <label>Куратор<select value={form.curatorId || ''} onChange={event => setForm({ ...form, curatorId: event.target.value })}><option value="">Без куратора</option>{users.filter(item => item.role === 'curator').map(item => <option key={item._id} value={item._id}>{item.firstName} {item.lastName}</option>)}</select></label>}</div>{form.role === 'student' && <div className="assignment-list"><strong>Назначенные курсы</strong>{courses.map(course => <label key={course._id}><input type="checkbox" checked={form.assignedCourses.includes(course._id)} onChange={event => setForm({ ...form, assignedCourses: event.target.checked ? [...form.assignedCourses, course._id] : form.assignedCourses.filter(id => id !== course._id) })} /> {course.title}</label>)}</div>}<button className="primary-button">{editId ? 'Сохранить' : 'Создать аккаунт'}</button></form>}
      <div className="people-list">{users.map(person => <div className="person-row" key={person._id}><PersonChip user={person} onNameClick={() => setViewing(person)} /><span className={`role-badge role-${person.role}`}>{roleNames[person.role]}</span><button className="text-action" onClick={() => beginEdit(person)}>Редактировать</button>{person.role === 'student' && <button className="text-action" onClick={() => navigate(`/students/${person._id}`)}>Прогресс</button>}<button className="icon-action danger" aria-label={`Удалить ${person.firstName}`} onClick={() => deleteUser(person)}><Trash2 size={17} /></button></div>)}{!users.length && <div className="table-empty">Пользователей пока нет</div>}</div></section>}
    {tab === 'courses' && <section className="dashboard-panel"><div className="dashboard-panel-head"><h2>Курсы</h2><span>{courses.length} курсов</span></div><div className="simple-list">{courses.map(course => <button key={course._id} onClick={() => navigate(route(course._id))}><span className="list-icon"><BookOpen size={20} /></span><span><strong>{course.title}</strong><small>{course.description}</small></span><ArrowRight size={18} /></button>)}</div></section>}
    {tab === 'progress' && <section className="dashboard-panel"><div className="dashboard-panel-head"><h2>Прогресс учеников</h2><span>Данные из пройденных уроков</span></div><div className="people-list">{progress.map(item => <button className="person-row progress-row" key={item.user._id} onClick={() => navigate(`/students/${item.user._id}`)}><PersonChip user={item.user} /><div className="row-progress"><ProgressBar percent={item.progress.percent} completed={item.progress.completedLessons} total={item.progress.totalLessons} /></div><ArrowRight size={18} /></button>)}{!progress.length && <div className="table-empty">Пока нет учеников</div>}</div></section>}
  </div>{viewing && <UserProfilePreview user={viewing} onClose={() => setViewing(null)} />}</main>;
}

function CuratorDashboard({ navigate }) {
  const [students, setStudents] = useState([]);
  const [summary, setSummary] = useState(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '' });
  const [error, setError] = useState('');
  const refresh = async () => { const [list, data] = await Promise.all([api('/curator/students'), api('/dashboard')]); setStudents(list); setSummary(data); };
  useEffect(() => { refresh().catch(err => setError(err.message)); }, []);
  const register = async event => { event.preventDefault(); setError(''); try { await post('/curator/students', form); setForm({ firstName: '', lastName: '', email: '', password: '' }); setCreating(false); await refresh(); } catch (err) { setError(err.message); } };
  return <main className="account-page"><div className="account-width"><PageHead eyebrow="КАБИНЕТ КУРАТОРА" title="Мои ученики" subtitle="Следите за обучением и помогайте каждому двигаться вперёд" action={<button className="primary-button" onClick={() => setCreating(true)}><Plus size={18} /> Зарегистрировать ученика</button>} />{error && <div className="form-error">{error}</div>}<div className="stats-grid compact"><Stat icon={Users} value={summary?.students ?? '—'} label="Моих учеников" tone="mint" /><Stat icon={Sparkles} value={summary ? `${summary.averageProgress}%` : '—'} label="Средний прогресс" /></div>
    {creating && <form className="account-form" onSubmit={register}><div className="panel-heading"><h3>Новый ученик</h3><button type="button" onClick={() => setCreating(false)}><X size={18} /></button></div><p>После регистрации ученик сразу появится в вашем списке.</p><div className="form-grid"><label>Имя<input required value={form.firstName} onChange={event => setForm({ ...form, firstName: event.target.value })} /></label><label>Фамилия<input required value={form.lastName} onChange={event => setForm({ ...form, lastName: event.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Пароль<input required type="password" minLength={10} value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label></div><button className="primary-button">Зарегистрировать ученика</button></form>}
    <section className="dashboard-panel"><div className="dashboard-panel-head"><h2>Список учеников</h2><span>{students.length} человек</span></div><div className="student-grid">{students.map(item => <button className="student-card" key={item._id} onClick={() => navigate(`/students/${item._id}`)}><PersonChip user={item} /><span className="student-card-sub">{item.progress.courses.length} курсов · последняя активность {item.progress.lastActivity ? new Date(item.progress.lastActivity).toLocaleDateString('ru-RU') : 'пока нет'}</span><ProgressBar percent={item.progress.percent} completed={item.progress.completedLessons} total={item.progress.totalLessons} /><span className="card-open">Открыть профиль <ArrowRight size={16} /></span></button>)}{!students.length && <div className="table-empty">У вас пока нет учеников. Зарегистрируйте первого.</div>}</div></section>
  </div></main>;
}

function TeacherDashboard({ user, courses, navigate }) {
  const [summary, setSummary] = useState(null);
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { api('/dashboard').then(setSummary).catch(err => setError(err.message)); }, []);
  const own = courses.filter(course => String(course.createdBy) === String(user._id));
  const create = async event => { event.preventDefault(); try { const course = await post('/courses', { title, description }); navigate(route(course._id)); } catch (err) { setError(err.message); } };
  return <main className="account-page"><div className="account-width"><PageHead eyebrow="КАБИНЕТ УЧИТЕЛЯ" title={`Здравствуйте, ${user.firstName}!`} subtitle="Создавайте курсы и материалы в знакомом редакторе" action={<button className="primary-button" onClick={() => setCreating(true)}><Plus size={18} /> Создать курс</button>} />{error && <div className="form-error">{error}</div>}<div className="stats-grid compact"><Stat icon={BookOpen} value={summary?.courses ?? '—'} label="Моих курсов" /><Stat icon={Sparkles} value={summary?.lessons ?? '—'} label="Уроков" tone="mint" /></div>{creating && <form className="account-form" onSubmit={create}><div className="panel-heading"><h3>Новый курс</h3><button type="button" onClick={() => setCreating(false)}><X size={18} /></button></div><div className="form-grid"><label>Название<input required value={title} onChange={event => setTitle(event.target.value)} /></label><label>Описание<input value={description} onChange={event => setDescription(event.target.value)} /></label></div><button className="primary-button">Создать курс</button></form>}<section className="dashboard-panel"><div className="dashboard-panel-head"><h2>Мои курсы</h2><span>{own.length} курсов</span></div><div className="simple-list">{own.map(course => <button key={course._id} onClick={() => navigate(route(course._id))}><span className="list-icon"><BookOpen size={20} /></span><span><strong>{course.title}</strong><small>{course.description || 'Откройте курс и продолжите редактирование'}</small></span><ArrowRight size={18} /></button>)}{!own.length && <div className="table-empty">Создайте первый курс, чтобы начать.</div>}</div></section></div></main>;
}

function StudentDashboard({ user, navigate }) {
  const [progress, setProgress] = useState(null);
  const [error, setError] = useState('');
  const [curatorInfo, setCuratorInfo] = useState({ loading: true, curator: null, error: '' });
  const [viewingCurator, setViewingCurator] = useState(null);
  useEffect(() => { api('/progress/me').then(setProgress).catch(err => setError(err.message)); }, []);
  useEffect(() => { let active = true; api('/profile/curator').then(data => { if (active) setCuratorInfo({ loading: false, curator: data.curator, error: '' }); }).catch(err => { if (active) setCuratorInfo({ loading: false, curator: null, error: err.message }); }); return () => { active = false; }; }, [user._id]);
  const openCuratorProfile = async () => { try { const data = await api('/profile/curator'); setViewingCurator(data.curator || curatorInfo.curator); } catch { setViewingCurator(curatorInfo.curator); } };
  return <main className="account-page learner-dashboard"><div className="account-width learner-dashboard-width">
    <header className="learner-dashboard-heading"><div><div className="eyebrow muted">МОЁ ОБУЧЕНИЕ</div><h1>Здравствуйте, {user.firstName}!</h1><p>Выберите курс и продолжайте с того места, где остановились.</p></div><span className="learner-heading-mark"><BookOpen size={24}/></span></header>
    {error && <div className="form-error">{error}</div>}
    <div className="learner-dashboard-grid">
      <section className="learner-courses-panel"><div className="learner-section-heading"><div><span className="learner-section-kicker">ВАША ПРОГРАММА</span><h2>Мои курсы</h2></div><span className="learner-course-count">{progress ? `${progress.courses.length} ${progress.courses.length === 1 ? 'курс' : 'курсов'}` : 'Загружаем…'}</span></div>
        <div className="learner-course-list">{progress?.courses.map(item => <article className="learner-course-card" key={item.courseId}><span className="learner-course-icon"><BookOpen size={22}/></span><div className="learner-course-main"><div className="learner-course-title-row"><h3>{item.title}</h3><span>{item.percent}%</span></div><ProgressBar percent={item.percent} completed={item.completedLessons} total={item.totalLessons}/><div className="learner-course-meta"><span>{item.completedLessons} из {item.totalLessons} уроков пройдено</span><button className="card-open" onClick={() => navigate(route(item.courseId))}>Продолжить <ArrowRight size={16}/></button></div></div></article>)}{progress && !progress.courses.length && <div className="learner-empty-courses"><BookOpen size={23}/><strong>Курсы ещё не назначены</strong><span>Обратитесь к куратору, чтобы он добавил курс в ваш кабинет.</span></div>}{!progress && <div className="learner-courses-loading">Загружаем ваши курсы…</div>}</div>
      </section>
      <aside className="learner-dashboard-aside">
        <section className="learner-progress-card"><span className="learner-section-kicker">ВАШ ПРОГРЕСС</span><div className="learner-progress-value">{progress ? `${progress.percent}%` : '—'}</div><ProgressBar percent={progress?.percent || 0} completed={progress?.completedLessons || 0} total={progress?.totalLessons || 0}/><p>{progress ? `${progress.completedLessons} из ${progress.totalLessons} уроков завершено` : 'Обновляем результаты обучения'}</p><div className="learner-progress-foot"><Check size={15}/>Прогресс сохраняется автоматически</div></section>
        <section className="learner-curator-card"><div className="learner-curator-title"><span className="learner-curator-icon"><UserRound size={18}/></span><div><span className="learner-section-kicker">ПОДДЕРЖКА</span><h2>Ваш куратор</h2></div></div>{curatorInfo.loading ? <p className="learner-curator-message">Загружаем данные куратора…</p> : curatorInfo.error ? <p className="learner-curator-message">Не удалось загрузить данные: {curatorInfo.error}</p> : curatorInfo.curator ? <div className="learner-curator-person"><span className="learner-curator-avatar">{curatorInfo.curator.avatar ? <img src={curatorInfo.curator.avatar} alt=""/> : initials(curatorInfo.curator)}</span><div className="learner-curator-details"><button type="button" className="person-name-action" onClick={openCuratorProfile}>{curatorInfo.curator.firstName} {curatorInfo.curator.lastName}</button><a href={`mailto:${curatorInfo.curator.email}`}><Mail size={14}/>{curatorInfo.curator.email}</a>{curatorInfo.curator.phone && <a href={`tel:${curatorInfo.curator.phone}`}><Phone size={14}/>{curatorInfo.curator.phone}</a>}</div></div> : <div className="learner-no-curator"><strong>Куратор пока не назначен</strong><span>Его имя и контакты появятся здесь, когда назначение будет сделано.</span></div>}</section>
      </aside>
    </div>
  </div>{viewingCurator && <UserProfilePreview user={viewingCurator} onClose={() => setViewingCurator(null)} />}</main>;
}

export function StudentDetail({ studentId, currentUser, courses, navigate }) {
  const [data, setData] = useState(null);
  const [selected, setSelected] = useState([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const load = async () => { const result = await api(currentUser.role === 'curator' ? `/curator/students/${studentId}` : `/progress/users/${studentId}`); setData(result); setSelected(result.user.assignedCourses || []); };
  useEffect(() => { load().catch(err => setError(err.message)); }, [studentId]);
  const saveAssignments = async () => { setSaving(true); setError(''); try { if (currentUser.role === 'curator') setData(await put(`/curator/students/${studentId}/courses`, { courseIds: selected })); else { await put(`/admin/users/${studentId}`, { assignedCourses: selected }); await load(); } } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <main className="account-page"><div className="account-width"><button className="back-link" onClick={() => navigate('/dashboard')}><ArrowLeft size={17} /> В кабинет</button>{error && <div className="form-error">{error}</div>}{data && <><PageHead eyebrow="ПРОФИЛЬ УЧЕНИКА" title={`${data.user.firstName} ${data.user.lastName}`} subtitle={data.user.email} /><div className="detail-layout"><section className="dashboard-panel"><h2>Обучение</h2>{data.progress.courses.length ? data.progress.courses.map(item => <div className="detail-course" key={item.courseId}><h3>{item.title}</h3><ProgressBar percent={item.percent} completed={item.completedLessons} total={item.totalLessons} /><h4>Уроки</h4><LessonChecklist lessons={item.lessons} /></div>) : <div className="table-empty">Курсы пока не назначены</div>}</section><aside className="detail-side"><div className="dashboard-panel"><h2>Об ученике</h2><dl><dt>Дата регистрации</dt><dd>{new Date(data.user.createdAt).toLocaleDateString('ru-RU')}</dd><dt>Последняя активность</dt><dd>{data.progress.lastActivity ? new Date(data.progress.lastActivity).toLocaleString('ru-RU') : 'Пока нет'}</dd><dt>Пройдено уроков</dt><dd>{data.progress.completedLessons} из {data.progress.totalLessons}</dd></dl></div><div className="dashboard-panel"><h2>Назначить курсы</h2><div className="assignment-list">{courses.map(course => <label key={course._id}><input type="checkbox" checked={selected.some(id => String(id) === String(course._id))} onChange={event => setSelected(event.target.checked ? [...selected, course._id] : selected.filter(id => String(id) !== String(course._id)))} /> {course.title}</label>)}</div><button className="primary-button" disabled={saving} onClick={saveAssignments}>{saving ? 'Сохраняем…' : 'Сохранить назначение'}</button></div></aside></div></>}</div></main>;
}
